import { useEffect, useState, useContext } from 'react';
import Head from 'next/head';
// eslint-disable-next-line import/named
// eslint-disable-next-line import/named
// import { useI18n } from 'next-localization';
import { requestContructor } from '../shared/helpers/api';
import HomePage from './home';
import { usePageDataContext } from '../shared/context/pageData-context';
import PageBuilder from '../shared/components/layout/pageBuilder';

function Static({ data, isAie }) {
  // const i18n = useI18n();
  const { setPageData } = usePageDataContext();
  const pageContent = data && data.page && data.page.segmentsMap;
  useEffect(() => {
    setPageData(data);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {i18n.t('title')} */}
        <HomePage pageContent={pageContent} />
        <PageBuilder pageContent={pageContent} />
      </main>
    </>
  );
}

Static.getInitialProps = async(context) => {
  const { req, query, res } = context; 
  // const headers = {};
  try{
    console.log('request req:::', req);
    console.log('request query:::', query);
    console.log('request query join:::', query.id.join('/'));
    const { data, error } = await requestContructor(query.id.join('/'), '', {}, true);
    return {
      data,
      // isAie:req.headers.host.endsWith('aienterprise.com')?true:false
    };
  }catch(e) {
    if(e?.response?.data?.status === 404) {
      // console.log('e?.response?.data',e?.response?.data);
      // res.writeHead(302, { Location: '/' });
      // res.end();
    }

    return {
      data: '',
    };
  }
};

export default Static;
