import React from 'react';

export default function HomePageRating() {
    return (
        <div className="row">
            <div className="redBox">
                <div className="col-sm-12" id="region-re1700010">
                    <div id="yotporatingscarousal_v1-wi2700005">
                        <div className="row ab-rating">
                            <div className="yotpo yotpo-reviews-carousel yotpo-size-6" data-background-color="transparent" data-mode="top_rated" data-type="both" data-count="9" data-show-bottomline="1" data-autoplay-enabled="1" data-autoplay-speed="3000" data-show-navigation="1" data-testimonials-page-enabled="1" data-testimonials-page-text="See All Reviews" data-testimonials-page-link="https://www.allenbrothers.com/ratings-and-reviews" data-yotpo-element-id="1"> <div className="yotpo-display-wrapper carousel-display-wrapper" data-attr-total-reviews="9"> <div className="carousel-read-more-text" data-text="Read More"></div> <span className="yotpo-icon yotpo-corner"></span>
                                <div className="label-with-tooltip carousel-tool-tip">
                                    <div className="yotpo-tool-tip" data-user-type="yotpo-verified-user">
                                        <div className="tool-tip-header">
                                            <span className="header-blue tool-tip-header-span"> Review Title</span>
                                        </div>
                                        <div className="tool-tip-content">
                                            Review Content
                                        </div>
                                    </div>
                                </div>
                                <div id="carousel-top-panel">
                                    <div role="heading" className="headline">Real Reviews From Real Customers</div>
                                    <div className="sr-only">Reviews carousel</div>  <div className="carousel-arrows">
                                        <div className="sr-only">Carousel arrows</div>
                                        <span className="yotpo-page-element yotpo-icon yotpo-icon-left-arrow-thin yotpo_previous" role="button" aria-label="Previous Page" tabindex="0"></span>
                                        <span className="yotpo-page-element yotpo-icon yotpo-icon-right-arrow-thin yotpo_next" role="button" aria-label="Next Page" tabindex="0"></span>
                                    </div>
                                    <div className="carousel-reviews-bottom-line ">
                                        <span className="yotpo-review-stars">
                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                            <span className="sr-only">4.8 star rating</span> </span>
                                        <span className="yotpo-num-of-reviews"> 3453 Reviews </span>
                                    </div>
                                    <div className="all-reviews ">
                                        <a target="_blank" href="https://www.allenbrothers.com/ratings-and-reviews" tabindex="0">See All Reviews</a></div>
                                </div> <div className="scroller">
                                    <div className="yotpo yotpo-carousel y-slider-container y-slide-left-animations">   <div role="list" className="y-slider-container y-slide-left-animations">
                                        <div role="listitem" className="standard-layout single-carousel review" data-review-id="420645075">
                                            <div className="big-version yotpo-hidden">
                                                <div className="product-link-container">
                                                    <div className="product-image-container pull-left">
                                                        <div className="y-carousel-product-image">
                                                            <div className="carousel-site-quote-container">
                                                                <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="right-side pull-right">
                                                    <div className="stars-container">
                                                        <span className="yotpo-stars carousel-stars">
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="sr-only">5.0 star rating</span> </span>
                                                        <span className="carousel-review-date" aria-label="review date 11/23/22"> 11/23/22 </span>
                                                    </div>
                                                    <div className="carousel-review-title" full-headline="Our experience with Allen Brothers"> Our experience with Allen Brothers </div>
                                                    <div className="carousel-review-body ">Our experience with Allen Brothers has been nothing but Exceptional. The quality in every product makes us keep coming back for th...
                                                        <div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Roy P.</div>
                                                </div> </div> <div className="small-version">
                                                <div className="stars-container">
                                                    <span className="yotpo-stars carousel-stars">
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="sr-only">5.0 star rating</span> </span>
                                                    <span className="carousel-review-date" aria-label="review date 11/23/22"> 11/23/22 </span>
                                                </div>
                                                <div className="carousel-review-title" full-headline="Our experience with Allen Brothers"> Our experience with Allen Brothers </div>
                                                <div className="product-link-container">
                                                    <div className="product-image-container pull-left">
                                                        <div className="y-carousel-product-image">
                                                            <div className="carousel-site-quote-container">
                                                                <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>
                                                    </div> </div> <div className="right-side pull-right">
                                                    <div className="carousel-review-body ">Our experience with Allen Brothers has been nothing but Exceptional. The quality in every product makes us keep coming back for th...
                                                        <div className="carousel-read-more" tabindex="0">Read More</div>
                                                    </div> <div className="carousel-review-author">Roy P.</div>
                                                </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="420886267">
                                            <div className="big-version yotpo-hidden">
                                                <a className="product-link-container" href="https://yotpo.com/go/2jmoxTeX" target="_blank" rel="nofollow">
                                                    <div className="product-image-container pull-left">
                                                        <div className="y-carousel-product-image">
                                                            <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551609/193891213/square.jpg?1630995295" alt="Product image for Wagyu Steak Burgers" />  </div>
                                                        <div className="product-name carousel-review-product-text">Wagyu Steak Burgers </div>
                                                    </div> </a> <div className="right-side pull-right"> <div className="stars-container">
                                                        <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                            <span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span>
                                                    </div> <div className="carousel-review-title" full-headline="My new favorite!"> My new favorite! </div>
                                                    <div className="carousel-review-body ">Absolutely amazing! Best flavor and great to prepare at home!</div>
                                                    <div className="carousel-review-author">Toni W.</div>
                                                </div> </div> <div className="small-version"> <div className="stars-container">
                                                    <span className="yotpo-stars carousel-stars">
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="My new favorite!"> My new favorite! </div>
                                                <a className="product-link-container" href="https://yotpo.com/go/2jmoxTeX" target="_blank" rel="nofollow">
                                                    <div className="product-image-container pull-left"> <div className="y-carousel-product-image">
                                                        <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551609/193891213/square.jpg?1630995295" alt="Product image for Wagyu Steak Burgers" />
                                                    </div>  <div className="product-name carousel-review-product-text">Wagyu Steak Burgers </div>
                                                    </div>
                                                </a>
                                                <div className="right-side pull-right"> <div className="carousel-review-body ">Absolutely amazing! Best flavor and great to prepare at home!</div>
                                                    <div className="carousel-review-author">Toni W.</div> </div> </div>
                                        </div>
                                        <div role="listitem" className="standard-layout single-carousel review" data-review-id="418582621" tabindex="0">
                                            <div className="big-version yotpo-hidden">
                                                <a className="product-link-container" href="https://yotpo.com/go/rdkAp3hn" target="_blank" rel="nofollow">
                                                    <div className="product-image-container pull-left">
                                                        <div className="y-carousel-product-image">
                                                            <img src="//cdn-yotpo-images-production.yotpo.com/Product/256058331/193891317/square.jpg?1630995547" alt="Product image for USDA Prime Filet Mignon: Complete-Trim" />
                                                        </div>  <div className="product-name carousel-review-product-text">USDA Prime Filet Mignon: Complete-Trim </div>  </div> </a>
                                                <div className="right-side pull-right">
                                                    <div className="stars-container"> <span className="yotpo-stars carousel-stars">
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span>
                                                        <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span>
                                                    </div>
                                                    <div className="carousel-review-title" full-headline="Our favorite for years. Absolutely"> Our favorite for years. Absolutely </div>
                                                    <div className="carousel-review-body ">Our favorite for years. Absolutely no waste - complete trim says it all.
                                                    </div> <div className="carousel-review-author">Howard S.</div>
                                                </div> </div> <div className="small-version">
                                                <div className="stars-container">
                                                    <span className="yotpo-stars carousel-stars">
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                                        </span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                                        </span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="Our favorite for years. Absolutely"> Our favorite for years. Absolutely </div>  <a className="product-link-container" href="https://yotpo.com/go/rdkAp3hn" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256058331/193891317/square.jpg?1630995547" alt="Product image for USDA Prime Filet Mignon: Complete-Trim" />
                                                </div>  <div className="product-name carousel-review-product-text">USDA Prime Filet Mignon: Complete-Trim </div>  </div> </a> <div className="right-side pull-right"> <div className="carousel-review-body ">Our favorite for years. Absolutely no waste - complete trim says it all.</div> <div className="carousel-review-author">Howard S.</div> </div> </div> </div>
                                        <div role="listitem" className="standard-layout single-carousel review" data-review-id="422057234" tabindex="0"> <div className="big-version yotpo-hidden">  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>  </div> </div> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                        </span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 12/01/22"> 12/01/22 </span> </div> <div className="carousel-review-title" full-headline="Courteous, prompt in shipping, very"> Courteous, prompt in shipping, very </div> <div className="carousel-review-body ">Courteous, prompt in shipping, very well packaged with lots of cold around them.</div>
                                            <div className="carousel-review-author">Pierre D.</div> </div> </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                            </span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 12/01/22"> 12/01/22 </span> </div> <div className="carousel-review-title" full-headline="Courteous, prompt in shipping, very"> Courteous, prompt in shipping, very </div>  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>  </div> </div> <div className="right-side pull-right"> <div className="carousel-review-body ">Courteous, prompt in shipping, very well packaged with lots of cold around them.</div> <div className="carousel-review-author">Pierre D.</div> </div> </div> </div>
                                        <div role="listitem" className="standard-layout single-carousel review" data-review-id="415842766" tabindex="0"> <div className="big-version yotpo-hidden">  <a className="product-link-container" href="https://yotpo.com/go/8ghUIW35" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256311424/193889504/square.jpg?1630993729" alt="Product image for Berkshire Bone-In Pork Chops" />
                                        </div>  <div className="product-name carousel-review-product-text">Berkshire Bone-In Pork Chops </div>  </div> </a> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                        </span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/04/22"> 11/04/22 </span> </div> <div className="carousel-review-title" full-headline="Excellent, flavorful tender pork chops!"> Excellent, flavorful tender pork chops! </div> <div className="carousel-review-body ">These pork chops were so good and tender! They had a nice flavor and needed very little seasoning. We fried them in Crisco with ga...<div className="carousel-read-more" tabindex="0">Read More</div>
                                                </div> <div className="carousel-review-author">Penny L.</div> </div> </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span>
                                                    <span className="carousel-review-date" aria-label="review date 11/04/22"> 11/04/22 </span> </div> <div className="carousel-review-title" full-headline="Excellent, flavorful tender pork chops!"> Excellent, flavorful tender pork chops! </div>  <a className="product-link-container" href="https://yotpo.com/go/8ghUIW35" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image" >  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256311424/193889504/square.jpg?1630993729" alt="Product image for Berkshire Bone-In Pork Chops" />  </div>
                                                        <div className="product-name carousel-review-product-text">Berkshire Bone-In Pork Chops </div>  </div> </a> <div className="right-side pull-right"> <div className="carousel-review-body ">These pork chops were so good and tender! They had a nice flavor and needed very little seasoning. We fried them in Crisco with ga...<div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Penny L.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="422021667"> <div className="big-version yotpo-hidden">  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>
                                                        </div> </div> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span>
                                                            <span className="carousel-review-date" aria-label="review date 12/01/22"> 12/01/22 </span> </div> <div className="carousel-review-title" full-headline="I have purchased from Allen"> I have purchased from Allen </div> <div className="carousel-review-body ">I have purchased from Allen Brothers for over 10 years. Steaks, chicken, seafood, burgers, hot dogs, veal, and pork. All are top n...<div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Cate A.</div> </div> </div> <div className="small-version"> <div className="stars-container">
                                                                <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 12/01/22"> 12/01/22 </span> </div> <div className="carousel-review-title" full-headline="I have purchased from Allen"> I have purchased from Allen </div>  <div className="product-link-container">
                                                    <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>
                                                    </div>  </div> </div> <div className="right-side pull-right"> <div className="carousel-review-body ">I have purchased from Allen Brothers for over 10 years. Steaks, chicken, seafood, burgers, hot dogs, veal, and pork. All are top n...<div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Cate A.</div> </div> </div>
                                        </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="419623760" > <div className="big-version yotpo-hidden">  <a className="product-link-container" href="https://yotpo.com/go/l4oXZQYF" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256549750/193890548/square.jpg?1630994328" alt="Product image for Carson's Ribs: Pre-cooked" />  </div>
                                            <div className="product-name carousel-review-product-text">Carson's Ribs: Pre-cooked </div>  </div> </a> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/19/22"> 11/19/22 </span> </div> <div className="carousel-review-title" full-headline="Very lean and tasty. Just"> Very lean and tasty. Just </div>
                                                <div className="carousel-review-body ">Very lean and tasty. Just the right amount of sauce, very tender.</div> <div className="carousel-review-author">William L.</div>
                                            </div> </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span>
                                                <span className="carousel-review-date" aria-label="review date 11/19/22"> 11/19/22 </span> </div> <div className="carousel-review-title" full-headline="Very lean and tasty. Just"> Very lean and tasty. Just </div>  <a className="product-link-container" href="https://yotpo.com/go/l4oXZQYF" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256549750/193890548/square.jpg?1630994328" alt="Product image for Carson's Ribs: Pre-cooked" />
                                                </div>  <div className="product-name carousel-review-product-text">Carson's Ribs: Pre-cooked </div>  </div> </a> <div className="right-side pull-right"> <div className="carousel-review-body ">Very lean and tasty. Just the right amount of sauce, very tender.</div> <div className="carousel-review-author">William L.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="420847470"> <div className="big-version yotpo-hidden">  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">
                                                    <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>
                                                </div> </div> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="Arrived to Soutg Georgia perfectly"> Arrived to Soutg Georgia perfectly </div> <div className="carousel-review-body ">Arrived to Soutg Georgia perfectly packed, frozen, with ample dry ice. Pdrfect</div> <div className="carousel-review-author">Jeff N.</div> </div> </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="Arrived to Soutg Georgia perfectly"> Arrived to Soutg Georgia perfectly </div>  <div className="product-link-container"> <div className="product-image-container pull-left">
                                                    <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>  </div>
                                                </div> <div className="right-side pull-right"> <div className="carousel-review-body ">Arrived to Soutg Georgia perfectly packed, frozen, with ample dry ice. Pdrfect</div> <div className="carousel-review-author">Jeff N.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="418492858"> <div className="big-version yotpo-hidden">  <a className="product-link-container" href="https://yotpo.com/go/q4fPsGM6" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551560/193890603/square.jpg?1630994412" alt="Product image for Maryland-Style Crab Cakes" />
                                                </div>  <div className="product-name carousel-review-product-text">Maryland-Style Crab Cakes </div>  </div> </a> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span> </div> <div className="carousel-review-title" full-headline="A little slice of heaven."> A little slice of heaven. </div> <div className="carousel-review-body ">I am addicted to these crab cakes. Consistently wonderful ! <br />Enough said.😁</div> <div className="carousel-review-author">Simeon G.</div> </div>
                                                </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="A little slice of heaven."> A little slice of heaven. </div>  <a className="product-link-container" href="https://yotpo.com/go/q4fPsGM6" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551560/193890603/square.jpg?1630994412" alt="Product image for Maryland-Style Crab Cakes" />  </div>  <div className="product-name carousel-review-product-text">Maryland-Style Crab Cakes </div>  </div> </a> <div className="right-side pull-right"> <div className="carousel-review-body ">I am addicted to these crab cakes. Consistently wonderful ! <br />Enough said. 😁</div>
                                                    <div className="carousel-review-author">Simeon G.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="420645075"> <div className="big-version yotpo-hidden">  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span>
                                                    </div>  </div>  </div> </div> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/23/22"> 11/23/22 </span>
                                                    </div> <div className="carousel-review-title" full-headline="Our experience with Allen Brothers"> Our experience with Allen Brothers </div> <div className="carousel-review-body ">Our experience with Allen Brothers has been nothing but Exceptional. The quality in every product makes us keep coming back for th...<div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Roy P.</div> </div> </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                                    </span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/23/22"> 11/23/22 </span> </div> <div className="carousel-review-title" full-headline="Our experience with Allen Brothers"> Our experience with Allen Brothers </div>  <div className="product-link-container"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <div className="carousel-site-quote-container"> <span className="yotpo-icon yotpo-icon-quote-left carousel-site-quote"></span> </div>  </div>  </div> </div> <div className="right-side pull-right"> <div className="carousel-review-body ">Our experience with Allen Brothers has been nothing but Exceptional. The quality in every product makes us keep coming back for th...<div className="carousel-read-more" tabindex="0">Read More</div></div> <div className="carousel-review-author">Roy P.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="420886267"> <div className="big-version yotpo-hidden">  <a className="product-link-container" href="https://yotpo.com/go/2jmoxTeX" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551609/193891213/square.jpg?1630995295" alt="Product image for Wagyu Steak Burgers" />  </div>  <div className="product-name carousel-review-product-text">Wagyu Steak Burgers </div>  </div> </a> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                        <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span> </div> <div className="carousel-review-title" full-headline="My new favorite!"> My new favorite! </div> <div className="carousel-review-body ">Absolutely amazing! Best flavor and great to prepare at home!</div> <div className="carousel-review-author">Toni W.</div> </div> </div> <div className="small-version">
                                                <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/24/22"> 11/24/22 </span> </div> <div className="carousel-review-title" full-headline="My new favorite!"> My new favorite! </div>  <a className="product-link-container" href="https://yotpo.com/go/2jmoxTeX" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256551609/193891213/square.jpg?1630995295" alt="Product image for Wagyu Steak Burgers" />  </div>  <div className="product-name carousel-review-product-text">Wagyu Steak Burgers </div>  </div> </a> <div className="right-side pull-right"> <div className="carousel-review-body ">Absolutely amazing! Best flavor and great to prepare at home!</div> <div className="carousel-review-author">Toni W.</div> </div> </div> </div>  <div role="listitem" className="standard-layout single-carousel review" data-review-id="418582621"> <div className="big-version yotpo-hidden">  <a className="product-link-container" href="https://yotpo.com/go/rdkAp3hn" target="_blank" rel="nofollow"> <div className="product-image-container pull-left"> <div className="y-carousel-product-image">  <img src="//cdn-yotpo-images-production.yotpo.com/Product/256058331/193891317/square.jpg?1630995547" alt="Product image for USDA Prime Filet Mignon: Complete-Trim" />  </div>  <div className="product-name carousel-review-product-text">USDA Prime Filet Mignon: Complete-Trim </div>  </div>
                                                </a> <div className="right-side pull-right"> <div className="stars-container"> <span className="yotpo-stars carousel-stars"> <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="sr-only">5.0 star rating</span>
                                                </span> <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="Our favorite for years. Absolutely"> Our favorite for years. Absolutely </div> <div className="carousel-review-body ">Our favorite for years. Absolutely no waste - complete trim says it all.</div>
                                                        <div className="carousel-review-author">Howard S.</div>
                                                    </div>
                                                </div> <div className="small-version"> <div className="stars-container"> <span className="yotpo-stars carousel-stars">
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span><span className="yotpo-icon yotpo-icon-star rating-star pull-left">
                                                    </span>
                                                    <span className="yotpo-icon yotpo-icon-star rating-star pull-left"></span>
                                                    <span className="sr-only">5.0 star rating</span> </span> <span className="carousel-review-date" aria-label="review date 11/15/22"> 11/15/22 </span>
                                                </div> <div className="carousel-review-title" full-headline="Our favorite for years. Absolutely"> Our favorite for years. Absolutely
                                                </div>
                                                <a className="product-link-container" href="https://yotpo.com/go/rdkAp3hn" target="_blank" rel="nofollow">
                                                    <div className="product-image-container pull-left">
                                                        <div className="y-carousel-product-image">
                                                            <img src="//cdn-yotpo-images-production.yotpo.com/Product/256058331/193891317/square.jpg?1630995547" alt="Product image for USDA Prime Filet Mignon: Complete-Trim" />
                                                        </div>
                                                        <div className="product-name carousel-review-product-text">USDA Prime Filet Mignon: Complete-Trim </div>  </div>
                                                </a> <div className="right-side pull-right"> <div className="carousel-review-body ">Our favorite for years. Absolutely no waste - complete trim says it all.</div> <div className="carousel-review-author">Howard S.</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    </div>
                                </div>
                                <div className="yotpo-label yotpo-small-box ">
                                    <a href="http://my.yotpo.com/landing_page?redirect=https%3A%2F%2Fwww.yotpo.com%2Fpowered-by-yotpo%2F&amp;utm_campaign=branding_link_reviews_widget_v2&amp;utm_medium=widget&amp;utm_source=allenbrothers.com" className="yotpo-logo-link-new" aria-label="Powered by Yotpo link to their homepage" tabindex="0" target="_blank">
                                        <span className="yotpo-logo-title  yotpo-powered "> Powered by </span>
                                        <div className="yotpo-icon-btn-big transparent-color-btn yotpo-logo-btn yotpo-icon yotpo-icon-yotpo-logo yotpo-logo-icon-new yotpo-icon yotpo-icon-yotpo-logo ">
                                        </div>
                                    </a> <div className="yotpo-logo-line"> </div>
                                    <div className="yotpo-clr">
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
